###
POST http://localhost:4000/api/usuario/register
Content-Type: application/json

{
    "nombre": "nacho",
    "apellido": "vidal",
    "email": "nacho@gmail.com",
    "pass": "123456"
}

###
POST http://localhost:4000/api/usuario/login
Content-Type: application/json

{
    "email": "nacho@gmail.com",
    "pass": "123456"
}